# Generated by Django 6.0.3 on 2026-03-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
