# Generated by Django 6.0.3 on 2026-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
