# Generated by Django 6.0.3 on 2026-03-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_configuracion_espacio_ingreso_reserva_salida_tarifa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tiempo_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='valor_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
